data(AirPassengers)
class(AirPassengers)
plot(AirPassengers)
abline(reg=lm(AirPassengers~time(AirPassengers)))
cycle(AirPassengers)
plot(aggregate(AirPassengers,FUN=mean))
boxplot(AirPassengers~cycle(AirPassengers))

library(tseries)
diff(log(AirPassengers))
acf(log(AirPassengers))
fit <- arima(log(AirPassengers), c(0, 1, 1),seasonal = list(order = c(0, 1, 1), period = 12))
pred <- predict(fit, n.ahead = 10*12)
ts.plot(AirPassengers,2.718^pred$pred, log = "y", lty = c(1,3))

library(devtools)
library(lattice)
library(latticeExtra)
library(gridExtra)
library(TSA)
library(pander)
library(zoo)
library(xts)

set.seed(1234)
data("larain")
plot(larain,ylab = 'inches', xlab = 'year' , type = 'o')
plot(y = larain,x = zlag(larain),ylab = 'Inches',xlab = 'Previous Year Inches')

data(color)
plot(color,ylab = 'Color Property',xlab = 'Batch',type = 'o')
plot(y = color,x = zlag(color),ylab = 'Color Property',xlab = 'Previous Batch Color Property')
len <- length(color)
cor(color[2:len],zlag(color)[2:len])

data(hare)
plot(hare,ylab='Abundance',xlab='Year',type='o')
plot(y=hare,x=zlag(hare),ylab='Abundance',xlab='Previous Year Abundance')
len <- length(hare)
cor(hare[2:len],zlag(hare)[2:len])